/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AutoramaController;
import Model.*;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nati_
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    private AutoramaController autorama;
    private final Dimension dimensaoPadrao;
    private ArrayList <Piloto> listaPilotosEquipe;
    private ArrayList <Carro> listaCarrosEquipe;
    private ArrayList <Carro> listaCarrosQualificacao;
    
    public TelaInicial(AutoramaController autorama) {
        this.autorama = autorama;
        this.dimensaoPadrao = new Dimension(817, 547);
        initComponents();
        esconderTelas();
        painelPrincipal.setPreferredSize(this.dimensaoPadrao);
        painelQualificacao.setPreferredSize(this.dimensaoPadrao);
        painelCadastroCarros.setPreferredSize(this.dimensaoPadrao);
        painelCadastroPilotos.setPreferredSize(this.dimensaoPadrao);
        painelCadastroEquipes.setPreferredSize(this.dimensaoPadrao);
        painelCadastroPista.setPreferredSize(this.dimensaoPadrao);
        this.listaCarrosEquipe = new ArrayList();
        this.listaCarrosQualificacao = new ArrayList();
        this.listaPilotosEquipe = new ArrayList();
        painelPrincipal.setVisible(true);
    }
    public TelaInicial() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCadastroCarros = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        inputMarcaCarro = new javax.swing.JTextField();
        inputNumeroCarro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        selectPilotoCarro = new javax.swing.JComboBox<>();
        SelectEquipeCarro = new javax.swing.JComboBox<>();
        inputIdCarro = new javax.swing.JTextField();
        botaoConfirmarCadastroCarro = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        inputTagCarro = new javax.swing.JTextField();
        inputModeloCarro = new javax.swing.JTextField();
        botaoVoltar = new javax.swing.JButton();
        botaoLerTAG = new javax.swing.JButton();
        painelCadastroPilotos = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        inputNomePiloto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        botaoConfirmarCadastroPiloto = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        inputApelidoPiloto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        selectCarroPiloto = new javax.swing.JComboBox<>();
        inputDataNascimentoPiloto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        selectEquipePiloto = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        selectAtividadePiloto = new javax.swing.JComboBox<>();
        inputIdPiloto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputPontosPiloto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        botaoVoltar1 = new javax.swing.JButton();
        selectNacionalidadePiloto = new javax.swing.JComboBox<>();
        imagemNacionalidadePiloto = new javax.swing.JLabel();
        painelCadastroEquipes = new javax.swing.JPanel();
        inputAnoEquipe = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        inputIdEquipe = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        inputPontosEquipe = new javax.swing.JTextField();
        inputNomeEquipe = new javax.swing.JTextField();
        inputApelidoEquipe = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        botaoConfirmarCadastroEquipe = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        botaoVoltar2 = new javax.swing.JButton();
        selectNacionalidadeEquipe = new javax.swing.JComboBox<>();
        botaoAdicionarPiloto = new javax.swing.JButton();
        botaoAdicionarCarro = new javax.swing.JButton();
        selectPilotoEquipe = new javax.swing.JComboBox<>();
        selectCarroEquipe = new javax.swing.JComboBox<>();
        imagemNacionalidadeEquipe = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaPilotosEquipe = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaCarrosEquipe = new javax.swing.JTable();
        painelPrincipal = new javax.swing.JPanel();
        botaoCadastrarCarros = new javax.swing.JButton();
        botaoCadastrarPilotos = new javax.swing.JButton();
        botaoCadastrarEquipes = new javax.swing.JButton();
        botaoCadastrarPista = new javax.swing.JButton();
        botaoQualificacao = new javax.swing.JButton();
        painelCadastroPista = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        selectNacionalidadePista = new javax.swing.JComboBox<>();
        imagemNacionalidadePista = new javax.swing.JLabel();
        inputNomePista = new javax.swing.JTextField();
        inputIdPista = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        botaoVoltar3 = new javax.swing.JButton();
        botaoConfirmarCadastroPista = new javax.swing.JButton();
        painelQualificacao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPilotosQualificacao = new javax.swing.JTable();
        selectPilotoQualificacao = new javax.swing.JComboBox<>();
        botaoAdicionarPilotoQualificcao = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        selectPistaQualificacao = new javax.swing.JComboBox<>();
        imagemNacionalidadePistaQualificacao = new javax.swing.JLabel();
        voltasQualificacao = new javax.swing.JSpinner();
        duracaoQualifiacao = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        botaoVoltar4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(817, 547));
        setMinimumSize(new java.awt.Dimension(817, 547));
        setPreferredSize(new java.awt.Dimension(817, 547));

        painelCadastroCarros.setBackground(new java.awt.Color(255, 255, 255));
        painelCadastroCarros.setMaximumSize(new java.awt.Dimension(817, 547));
        painelCadastroCarros.setMinimumSize(new java.awt.Dimension(817, 547));

        jLabel14.setText("Marca");

        jLabel15.setText("Número");

        jLabel16.setText("Piloto");

        jLabel17.setText("Equipe");

        selectPilotoCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPilotoCarroActionPerformed(evt);
            }
        });

        SelectEquipeCarro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SelectEquipeCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectEquipeCarroActionPerformed(evt);
            }
        });

        inputIdCarro.setEditable(false);

        botaoConfirmarCadastroCarro.setText("Cadastrar");
        botaoConfirmarCadastroCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarCadastroCarroActionPerformed(evt);
            }
        });

        jLabel13.setText("ID");

        jSeparator2.setBackground(new java.awt.Color(0, 102, 255));

        jLabel3.setText("TAG");

        jLabel12.setText("Modelo");

        inputTagCarro.setEditable(false);

        botaoVoltar.setText("Cancelar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoLerTAG.setText("Ler TAG");
        botaoLerTAG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLerTAGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCadastroCarrosLayout = new javax.swing.GroupLayout(painelCadastroCarros);
        painelCadastroCarros.setLayout(painelCadastroCarrosLayout);
        painelCadastroCarrosLayout.setHorizontalGroup(
            painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroCarrosLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13)
                    .addGroup(painelCadastroCarrosLayout.createSequentialGroup()
                        .addComponent(inputIdCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(240, 240, 240)
                        .addComponent(botaoLerTAG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroCarrosLayout.createSequentialGroup()
                            .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(inputTagCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(38, 38, 38)
                            .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(inputModeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelCadastroCarrosLayout.createSequentialGroup()
                        .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(selectPilotoCarro, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputMarcaCarro, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15)
                            .addComponent(inputNumeroCarro)
                            .addComponent(jLabel17)
                            .addComponent(SelectEquipeCarro, 0, 182, Short.MAX_VALUE)
                            .addComponent(botaoConfirmarCadastroCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        painelCadastroCarrosLayout.setVerticalGroup(
            painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroCarrosLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputIdCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoLerTAG, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTagCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputModeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputMarcaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNumeroCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectPilotoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectEquipeCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoConfirmarCadastroCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        painelCadastroPilotos.setBackground(new java.awt.Color(255, 255, 255));
        painelCadastroPilotos.setMaximumSize(new java.awt.Dimension(817, 547));
        painelCadastroPilotos.setMinimumSize(new java.awt.Dimension(817, 547));

        jSeparator1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel9.setText("Em atividade");

        jLabel10.setText("Pontos");

        botaoConfirmarCadastroPiloto.setText("Cadastrar");
        botaoConfirmarCadastroPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarCadastroPilotoActionPerformed(evt);
            }
        });

        jLabel11.setText("ID");

        jLabel1.setText("Nome do Piloto");

        inputApelidoPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputApelidoPilotoActionPerformed(evt);
            }
        });

        jLabel2.setText("Carro");

        selectCarroPiloto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Apelido");

        selectEquipePiloto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Data de Nascimento");

        selectAtividadePiloto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Nao" }));
        selectAtividadePiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAtividadePilotoActionPerformed(evt);
            }
        });

        inputIdPiloto.setEditable(false);

        jLabel7.setText("Equipe");

        inputPontosPiloto.setEditable(false);

        jLabel8.setText("Nacionalidade");

        botaoVoltar1.setText("Cancelar");
        botaoVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltar1ActionPerformed(evt);
            }
        });

        selectNacionalidadePiloto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        imagemNacionalidadePiloto.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        imagemNacionalidadePiloto.setText(" ");

        javax.swing.GroupLayout painelCadastroPilotosLayout = new javax.swing.GroupLayout(painelCadastroPilotos);
        painelCadastroPilotos.setLayout(painelCadastroPilotosLayout);
        painelCadastroPilotosLayout.setHorizontalGroup(
            painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroPilotosLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(painelCadastroPilotosLayout.createSequentialGroup()
                            .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(painelCadastroPilotosLayout.createSequentialGroup()
                                    .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(selectAtividadePiloto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(selectCarroPiloto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(inputNomePiloto, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                                        .addGroup(painelCadastroPilotosLayout.createSequentialGroup()
                                                            .addComponent(selectNacionalidadePiloto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addGap(4, 4, 4)
                                                            .addComponent(imagemNacionalidadePiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addComponent(jLabel8)))
                                            .addComponent(jLabel2))
                                        .addComponent(jLabel9)
                                        .addComponent(botaoVoltar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(40, 40, 40))
                                .addGroup(painelCadastroPilotosLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(209, 209, 209))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelCadastroPilotosLayout.createSequentialGroup()
                                    .addComponent(inputIdPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(inputApelidoPiloto)
                                .addComponent(inputDataNascimentoPiloto, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                .addComponent(selectEquipePiloto, 0, 166, Short.MAX_VALUE)
                                .addComponent(botaoConfirmarCadastroPiloto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(inputPontosPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        painelCadastroPilotosLayout.setVerticalGroup(
            painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroPilotosLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputIdPiloto)
                    .addComponent(inputPontosPiloto))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputApelidoPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelCadastroPilotosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(inputNomePiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroPilotosLayout.createSequentialGroup()
                        .addComponent(selectNacionalidadePiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelCadastroPilotosLayout.createSequentialGroup()
                        .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputDataNascimentoPiloto, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(imagemNacionalidadePiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(selectCarroPiloto)
                    .addComponent(selectEquipePiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(selectAtividadePiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoConfirmarCadastroPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelCadastroPilotosLayout.createSequentialGroup()
                        .addComponent(botaoVoltar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(81, 81, 81))
        );

        painelCadastroEquipes.setBackground(new java.awt.Color(255, 255, 255));
        painelCadastroEquipes.setMaximumSize(new java.awt.Dimension(817, 547));
        painelCadastroEquipes.setMinimumSize(new java.awt.Dimension(817, 547));

        jLabel29.setText("Ano");

        inputIdEquipe.setEditable(false);

        jLabel25.setText("Pilotos");

        jLabel26.setText("Pontos");

        jLabel27.setText("ID");

        inputPontosEquipe.setEditable(false);

        inputApelidoEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputApelidoEquipeActionPerformed(evt);
            }
        });

        jLabel21.setText("Carros");

        botaoConfirmarCadastroEquipe.setText("Cadastrar");
        botaoConfirmarCadastroEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarCadastroEquipeActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 102, 255));

        jLabel22.setText("Nacionalidade");

        jLabel28.setText("Apelido");

        jLabel23.setText("Nome ");

        botaoVoltar2.setText("Cancelar");
        botaoVoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltar2ActionPerformed(evt);
            }
        });

        selectNacionalidadeEquipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botaoAdicionarPiloto.setText("+");
        botaoAdicionarPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarPilotoActionPerformed(evt);
            }
        });

        botaoAdicionarCarro.setText("+");
        botaoAdicionarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarCarroActionPerformed(evt);
            }
        });

        selectPilotoEquipe.setEditable(true);
        selectPilotoEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPilotoEquipeActionPerformed(evt);
            }
        });

        selectCarroEquipe.setEditable(true);
        selectCarroEquipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        imagemNacionalidadeEquipe.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        imagemNacionalidadeEquipe.setText(" ");

        tabelaPilotosEquipe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pilotos "
            }
        ));
        jScrollPane3.setViewportView(tabelaPilotosEquipe);

        tabelaCarrosEquipe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carros "
            }
        ));
        jScrollPane4.setViewportView(tabelaCarrosEquipe);

        javax.swing.GroupLayout painelCadastroEquipesLayout = new javax.swing.GroupLayout(painelCadastroEquipes);
        painelCadastroEquipes.setLayout(painelCadastroEquipesLayout);
        painelCadastroEquipesLayout.setHorizontalGroup(
            painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(botaoVoltar2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(260, 260, 260)
                                .addComponent(jLabel28))
                            .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                                .addComponent(inputNomeEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(inputApelidoEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroEquipesLayout.createSequentialGroup()
                                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputIdEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(inputPontosEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                        .addComponent(inputAnoEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selectNacionalidadeEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imagemNacionalidadeEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                        .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                                .addComponent(selectPilotoEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoAdicionarPiloto))
                            .addComponent(jLabel25)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21)
                            .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                                .addComponent(selectCarroEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoAdicionarCarro))
                            .addComponent(botaoConfirmarCadastroEquipe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(185, 185, 185))))
        );
        painelCadastroEquipesLayout.setVerticalGroup(
            painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPontosEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputIdEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel28))
                .addGap(6, 6, 6)
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputNomeEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputApelidoEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel29))
                    .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputAnoEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectNacionalidadeEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagemNacionalidadeEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectPilotoEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAdicionarPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectCarroEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAdicionarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltar2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoConfirmarCadastroEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        painelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        painelPrincipal.setMaximumSize(new java.awt.Dimension(817, 547));
        painelPrincipal.setMinimumSize(new java.awt.Dimension(817, 547));
        painelPrincipal.setPreferredSize(new java.awt.Dimension(817, 547));

        botaoCadastrarCarros.setText("Cadastrar Carros");
        botaoCadastrarCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarCarrosActionPerformed(evt);
            }
        });

        botaoCadastrarPilotos.setText("Cadastrar Pilotos");
        botaoCadastrarPilotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarPilotosActionPerformed(evt);
            }
        });

        botaoCadastrarEquipes.setText("Cadastrar Equipes");
        botaoCadastrarEquipes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarEquipesActionPerformed(evt);
            }
        });

        botaoCadastrarPista.setText("Cadastrar Pista");
        botaoCadastrarPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarPistaActionPerformed(evt);
            }
        });

        botaoQualificacao.setText("Qualificação");
        botaoQualificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoQualificacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoCadastrarEquipes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoCadastrarPilotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoCadastrarCarros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoCadastrarPista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoQualificacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(374, Short.MAX_VALUE))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(botaoCadastrarCarros)
                .addGap(18, 18, 18)
                .addComponent(botaoCadastrarPilotos)
                .addGap(18, 18, 18)
                .addComponent(botaoCadastrarEquipes)
                .addGap(18, 18, 18)
                .addComponent(botaoCadastrarPista)
                .addGap(18, 18, 18)
                .addComponent(botaoQualificacao)
                .addContainerGap(423, Short.MAX_VALUE))
        );

        painelCadastroPista.setBackground(new java.awt.Color(255, 255, 255));
        painelCadastroPista.setMaximumSize(new java.awt.Dimension(817, 547));
        painelCadastroPista.setMinimumSize(new java.awt.Dimension(817, 547));

        jLabel30.setText("ID");

        selectNacionalidadePista.setEditable(true);
        selectNacionalidadePista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        imagemNacionalidadePista.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        imagemNacionalidadePista.setText(" ");

        inputIdPista.setEditable(false);

        jSeparator4.setBackground(new java.awt.Color(0, 102, 255));

        jLabel24.setText("Nacionalidade");

        jLabel34.setText("Nome ");

        botaoVoltar3.setText("Cancelar");
        botaoVoltar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltar3ActionPerformed(evt);
            }
        });

        botaoConfirmarCadastroPista.setText("Cadastrar");
        botaoConfirmarCadastroPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarCadastroPistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCadastroPistaLayout = new javax.swing.GroupLayout(painelCadastroPista);
        painelCadastroPista.setLayout(painelCadastroPistaLayout);
        painelCadastroPistaLayout.setHorizontalGroup(
            painelCadastroPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroPistaLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(painelCadastroPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroPistaLayout.createSequentialGroup()
                        .addComponent(botaoVoltar3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelCadastroPistaLayout.createSequentialGroup()
                        .addGroup(painelCadastroPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelCadastroPistaLayout.createSequentialGroup()
                                .addGroup(painelCadastroPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputNomePista, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34))
                                .addGap(110, 110, 110)
                                .addGroup(painelCadastroPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(selectNacionalidadePista, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(inputIdPista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelCadastroPistaLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(459, 459, 459))
                            .addComponent(botaoConfirmarCadastroPista, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imagemNacionalidadePista, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 135, Short.MAX_VALUE))))
        );
        painelCadastroPistaLayout.setVerticalGroup(
            painelCadastroPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroPistaLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputIdPista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(painelCadastroPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel24))
                .addGroup(painelCadastroPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroPistaLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(painelCadastroPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNomePista, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectNacionalidadePista, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelCadastroPistaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(imagemNacionalidadePista, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(painelCadastroPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltar3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoConfirmarCadastroPista, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116))
        );

        painelQualificacao.setBackground(new java.awt.Color(255, 255, 255));
        painelQualificacao.setMaximumSize(new java.awt.Dimension(817, 547));
        painelQualificacao.setMinimumSize(new java.awt.Dimension(817, 547));
        painelQualificacao.setPreferredSize(new java.awt.Dimension(817, 547));

        tabelaPilotosQualificacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Apelido", "Nacionalidade", "Equipe", "Carro"
            }
        ));
        jScrollPane1.setViewportView(tabelaPilotosQualificacao);

        selectPilotoQualificacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectPilotoQualificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPilotoQualificacaoActionPerformed(evt);
            }
        });

        botaoAdicionarPilotoQualificcao.setText("+");
        botaoAdicionarPilotoQualificcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarPilotoQualificcaoActionPerformed(evt);
            }
        });

        jLabel6.setText("Piloto");

        jLabel18.setText("Pista");

        selectPistaQualificacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        imagemNacionalidadePistaQualificacao.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        imagemNacionalidadePistaQualificacao.setText(" ");

        jLabel19.setText("Voltas");

        jLabel20.setText("Duração (min.)");

        botaoVoltar4.setText("Cancelar");
        botaoVoltar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelQualificacaoLayout = new javax.swing.GroupLayout(painelQualificacao);
        painelQualificacao.setLayout(painelQualificacaoLayout);
        painelQualificacaoLayout.setHorizontalGroup(
            painelQualificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelQualificacaoLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(painelQualificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoVoltar4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelQualificacaoLayout.createSequentialGroup()
                        .addComponent(selectPilotoQualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoAdicionarPilotoQualificcao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelQualificacaoLayout.createSequentialGroup()
                        .addGroup(painelQualificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelQualificacaoLayout.createSequentialGroup()
                                .addComponent(selectPistaQualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(imagemNacionalidadePistaQualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelQualificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(voltasQualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(82, 82, 82)
                        .addGroup(painelQualificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(duracaoQualifiacao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(90, 90, 90))
        );
        painelQualificacaoLayout.setVerticalGroup(
            painelQualificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelQualificacaoLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelQualificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(selectPilotoQualificacao)
                    .addComponent(botaoAdicionarPilotoQualificcao, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelQualificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelQualificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectPistaQualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagemNacionalidadePistaQualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelQualificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(voltasQualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(duracaoQualifiacao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(botaoVoltar4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelCadastroCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelCadastroPilotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelCadastroEquipes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelCadastroPista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelQualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(painelCadastroCarros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(painelCadastroPilotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(painelCadastroEquipes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 445, Short.MAX_VALUE)
                    .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                    .addGap(0, 447, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelCadastroPista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelQualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoConfirmarCadastroCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarCadastroCarroActionPerformed
        String marcaCarro = inputMarcaCarro.getText();
        String modeloCarro = inputModeloCarro.getText();
        String numeroCarro = inputNumeroCarro.getText();
        String tagCarro = inputTagCarro.getText();
        String idCarro = inputIdCarro.getText();
        String pilotoSelecionado = (String) selectPilotoCarro.getSelectedItem();
        String equipeSelecionada = (String) SelectEquipeCarro.getSelectedItem();
        Carro carroCadastrado = new Carro(idCarro, "TAGTESTE", modeloCarro, marcaCarro, numeroCarro);
        if(pilotoSelecionado != "<Selecionar Piloto>"){
            Piloto piloto = buscaPilotoNome(pilotoSelecionado);
            if(piloto != null){
                carroCadastrado.setPiloto(piloto);
            }
        }
        if(equipeSelecionada != "<Selecionar Equipe>"){
            Equipe equipe = buscaEquipeNome(equipeSelecionada);
            if(equipe != null){
                carroCadastrado.setEquipe(equipe);
            }
        }
        if(carroCadastrado != null){
            autorama.cadastrarCarro(carroCadastrado);
            JOptionPane.showMessageDialog(rootPane, "Carro cadastrado com sucesso!");
            inputMarcaCarro.setText("");
            inputModeloCarro.setText("");
            inputNumeroCarro.setText("");
            inputTagCarro.setText("");
            inputIdCarro.setText("");
        }
        esconderTelas();
        painelPrincipal.setVisible(true);
    }//GEN-LAST:event_botaoConfirmarCadastroCarroActionPerformed

    private void botaoConfirmarCadastroPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarCadastroPilotoActionPerformed
        String id = inputIdPiloto.getText();
        String nome = inputNomePiloto.getText();
        String apelido = inputApelidoPiloto.getText();
        String nacionalidade = (String) selectNacionalidadePiloto.getSelectedItem();
        String equipeSelecionada = (String) selectEquipePiloto.getSelectedItem();
        String carroSelecionado = (String) selectCarroPiloto.getSelectedItem();
        if(nacionalidade == "<Selecionar Nacionalidade>"){
            return;
        }
        String statusAtividade = (String) selectAtividadePiloto.getSelectedItem();
        boolean emAtividade = true;
        if(statusAtividade == "Nao"){
            emAtividade = false;
        }
        Piloto pilotoCadastrado = new Piloto(id, nome, apelido,  nacionalidade, emAtividade);
        if(equipeSelecionada != "<Selecionar Equipe>"){
            Equipe equipe = buscaEquipeNome(equipeSelecionada);
            if(equipe != null){
                pilotoCadastrado.setEquipe(equipe);
            }
        }
        if(carroSelecionado != "<Selecionar Carro>"){
            Carro carro = buscaCarroMarca(carroSelecionado);
            if(carro != null){
                pilotoCadastrado.setCarro(carro);
            }
        }
        if(pilotoCadastrado != null){
            autorama.cadastrarPiloto(pilotoCadastrado);
            JOptionPane.showMessageDialog(rootPane, "Piloto cadastrado com sucesso!");
            inputIdPiloto.setText("");
            inputNomePiloto.setText("");
            inputApelidoPiloto.setText("");
        }
        esconderTelas();
        painelPrincipal.setVisible(true);
    }//GEN-LAST:event_botaoConfirmarCadastroPilotoActionPerformed

    private void inputApelidoPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputApelidoPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputApelidoPilotoActionPerformed

    private void botaoCadastrarCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarCarrosActionPerformed
        int id = autorama.getCarros().size() + 1;
        inputIdCarro.setText(Integer.toString(id));
        esconderTelas();
        preenchePilotos();
        preencheEquipesCarro();
        painelCadastroCarros.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarCarrosActionPerformed

    private void botaoCadastrarPilotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarPilotosActionPerformed
        int id = autorama.getPilotos().size() + 1;
        inputIdPiloto.setText(Integer.toString(id));
        inputPontosPiloto.setText("000");
        preencheEquipesPiloto();
        preencheNacionalidadePiloto();
        preencheCarros();
        esconderTelas();
        selectNacionalidadePiloto.addActionListener((ActionEvent e) -> {
            try {
                String pais_selecionado = selectNacionalidadePiloto.getSelectedItem().toString();
                Pais pais = autorama.getPais(pais_selecionado);
                
                BufferedImage img_bf = ImageIO.read(new File(pais.getBandeira()));
                ImageIcon img = new ImageIcon(img_bf);
                img = new ImageIcon(img.getImage().getScaledInstance(44, 32, java.awt.Image.SCALE_DEFAULT));
                imagemNacionalidadePiloto.setIcon(img);
                
            } catch (IOException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {}
        });
        painelCadastroPilotos.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarPilotosActionPerformed

    private void botaoCadastrarEquipesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarEquipesActionPerformed
        limpaTabela();
        int id = autorama.getEquipes().size() + 1;
        inputIdEquipe.setText(Integer.toString(id));
        inputPontosEquipe.setText("000");
        preencheCarrosEquipe();
        preenchePilotosEquipe();
        preencheNacionalidadeEquipe();
        esconderTelas();
        selectNacionalidadeEquipe.addActionListener((ActionEvent e) -> {
            try {
                String pais_selecionado = selectNacionalidadeEquipe.getSelectedItem().toString();
                Pais pais = autorama.getPais(pais_selecionado);
                
                BufferedImage img_bf = ImageIO.read(new File(pais.getBandeira()));
                ImageIcon img = new ImageIcon(img_bf);
                img = new ImageIcon(img.getImage().getScaledInstance(44, 32, java.awt.Image.SCALE_DEFAULT));
                imagemNacionalidadeEquipe.setIcon(img);
                
            } catch (IOException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {}
        });
        painelCadastroEquipes.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarEquipesActionPerformed

    private void selectPilotoCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPilotoCarroActionPerformed

    }//GEN-LAST:event_selectPilotoCarroActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        esconderTelas();
        painelPrincipal.setVisible(true);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltar1ActionPerformed
        esconderTelas();
        painelPrincipal.setVisible(true);
    }//GEN-LAST:event_botaoVoltar1ActionPerformed

    private void SelectEquipeCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectEquipeCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectEquipeCarroActionPerformed

    private void selectAtividadePilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAtividadePilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectAtividadePilotoActionPerformed

    private void selectPilotoEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPilotoEquipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectPilotoEquipeActionPerformed

    private void botaoVoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltar2ActionPerformed
        esconderTelas();
        painelPrincipal.setVisible(true);
    }//GEN-LAST:event_botaoVoltar2ActionPerformed

    private void botaoConfirmarCadastroEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarCadastroEquipeActionPerformed
        String nome = inputNomeEquipe.getText();
        String apelido = inputApelidoEquipe.getText();
        String ano = inputAnoEquipe.getText();
        String id = inputIdEquipe.getText();
        String nacionalidade = (String) selectNacionalidadeEquipe.getSelectedItem();
        if(nacionalidade == "<Selecionar Nacionalidade>"){
            return;
        }
        if(this.listaCarrosEquipe.isEmpty() || this.listaPilotosEquipe.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Insira pilotos e carros.");
            return;
        }
        Equipe equipeCadastrada = new Equipe(id, nome, apelido, nacionalidade, ano);
        equipeCadastrada.setLisatCarros(this.listaCarrosEquipe);
        equipeCadastrada.setListaPilotos(this.listaPilotosEquipe);
        if(equipeCadastrada != null){
            autorama.cadastrarEquipe(equipeCadastrada);
            JOptionPane.showMessageDialog(rootPane, "Equipe cadastrada com sucesso!");
            inputNomeEquipe.setText("");
            inputApelidoEquipe.setText("");
            inputAnoEquipe.setText("");
        }
        esconderTelas();
        painelPrincipal.setVisible(true);
    }//GEN-LAST:event_botaoConfirmarCadastroEquipeActionPerformed

    private void inputApelidoEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputApelidoEquipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputApelidoEquipeActionPerformed

    private void botaoAdicionarPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarPilotoActionPerformed
        String selecionado = (String) selectPilotoEquipe.getSelectedItem();
        if(selecionado != "<Selecionar Piloto>"){
            DefaultTableModel tabela = (DefaultTableModel) tabelaPilotosEquipe.getModel();
            tabela.addRow (new String [] {selecionado}); 
            Piloto piloto = buscaPilotoNome(selecionado);
            this.listaPilotosEquipe.add(piloto);
            selectPilotoEquipe.removeItem((Object) selecionado);
        } else{
            JOptionPane.showMessageDialog(rootPane, "Selecione uma opção.");
        }
    }//GEN-LAST:event_botaoAdicionarPilotoActionPerformed

    private void botaoAdicionarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarCarroActionPerformed
        String selecionado = (String) selectCarroEquipe.getSelectedItem();
        if(selecionado != "<Selecionar Carro>"){
            DefaultTableModel tabela = (DefaultTableModel) tabelaCarrosEquipe.getModel();
            tabela.addRow (new String [] {selecionado});
            Carro carro = buscaCarroMarca(selecionado);
            this.listaCarrosEquipe.add(carro);
            selectCarroEquipe.removeItem((Object) selecionado);
        } else{
            JOptionPane.showMessageDialog(rootPane, "Selecione uma opção.");
        }
    }//GEN-LAST:event_botaoAdicionarCarroActionPerformed

    private void botaoCadastrarPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarPistaActionPerformed
        int id = autorama.getPistas().size() + 1;
        inputIdPista.setText(Integer.toString(id));
        preencheNacionalidadePista();
        esconderTelas();
        selectNacionalidadePista.addActionListener((ActionEvent e) -> {
            try {
                String pais_selecionado = selectNacionalidadePista.getSelectedItem().toString();
                Pais pais = autorama.getPais(pais_selecionado);
                
                BufferedImage img_bf = ImageIO.read(new File(pais.getBandeira()));
                ImageIcon img = new ImageIcon(img_bf);
                img = new ImageIcon(img.getImage().getScaledInstance(44, 32, java.awt.Image.SCALE_DEFAULT));
                imagemNacionalidadePista.setIcon(img);
                
            } catch (IOException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {}
        });
        painelCadastroPista.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarPistaActionPerformed

    private void botaoVoltar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltar3ActionPerformed
        esconderTelas();
        painelPrincipal.setVisible(true);
    }//GEN-LAST:event_botaoVoltar3ActionPerformed

    private void botaoConfirmarCadastroPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarCadastroPistaActionPerformed
        String nome = inputNomePista.getText();
        String id = inputIdPista.getText();
        String nacionalidade = (String) selectNacionalidadePista.getSelectedItem();
        if(nacionalidade == "<Selecionar Nacionalidade>"){
            return;
        }
        Pista pistaCadastrada = autorama.cadastrarPista(id, nome, nacionalidade);
       
        if(pistaCadastrada != null){
            JOptionPane.showMessageDialog(rootPane, "Pista cadastrada com sucesso!");
            inputNomePista.setText("");
        }
        esconderTelas();
        painelPrincipal.setVisible(true);
    }//GEN-LAST:event_botaoConfirmarCadastroPistaActionPerformed

    private void botaoQualificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoQualificacaoActionPerformed
        esconderTelas();
        preenchePilotosQualificacao();
        preenchePistas();
        selectPistaQualificacao.addActionListener((ActionEvent e) -> {
            try {
                Pista pista = buscaPistaNome(selectPistaQualificacao.getSelectedItem().toString());
                Pais pais = autorama.getPais(pista.getPais());
                
                BufferedImage img_bf = ImageIO.read(new File(pais.getBandeira()));
                ImageIcon img = new ImageIcon(img_bf);
                img = new ImageIcon(img.getImage().getScaledInstance(44, 32, java.awt.Image.SCALE_DEFAULT));
                imagemNacionalidadePistaQualificacao.setIcon(img);
                
            } catch (IOException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {}
        });
        painelQualificacao.setVisible(true);
    }//GEN-LAST:event_botaoQualificacaoActionPerformed

    private void selectPilotoQualificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPilotoQualificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectPilotoQualificacaoActionPerformed

    private void botaoAdicionarPilotoQualificcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarPilotoQualificcaoActionPerformed
        String selecionado = (String) selectPilotoQualificacao.getSelectedItem();
        if(selecionado != "<Selecionar Piloto>"){
            DefaultTableModel tabela = (DefaultTableModel)tabelaPilotosQualificacao.getModel();
            Piloto piloto = buscaPilotoNome(selecionado);
            if(this.listaCarrosQualificacao.contains(piloto.getCarro())){
                JOptionPane.showMessageDialog(rootPane, "O carro associado a este piloto já está na pista.");
                selectPilotoQualificacao.removeItem((Object) selecionado);
                return;
            }
            tabela.addRow (new String [] {piloto.getNome(), piloto.getApelido(), piloto.getNacionalidade(), piloto.getEquipe().getNome(), piloto.getCarro().getMarca()}); 
            selectPilotoQualificacao.removeItem((Object) selecionado);
            listaCarrosQualificacao.add(piloto.getCarro());
        } else{
            JOptionPane.showMessageDialog(rootPane, "Selecione uma opção.");
        }
    }//GEN-LAST:event_botaoAdicionarPilotoQualificcaoActionPerformed

    private void botaoVoltar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltar4ActionPerformed
        esconderTelas();
        limpaTabelaQualificacao();
        painelPrincipal.setVisible(true);
    }//GEN-LAST:event_botaoVoltar4ActionPerformed

    private void botaoLerTAGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLerTAGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoLerTAGActionPerformed
                              
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
    
    private void esconderTelas(){
        painelCadastroCarros.setVisible(false);
        painelCadastroPilotos.setVisible(false);
        painelCadastroEquipes.setVisible(false);
        painelPrincipal.setVisible(false);
        painelCadastroPista.setVisible(false);
        painelQualificacao.setVisible(false);
    }
    
    public void limpaTabela(){
        DefaultTableModel tblRemove1 = (DefaultTableModel)tabelaPilotosEquipe.getModel();
        DefaultTableModel tblRemove2 = (DefaultTableModel)tabelaCarrosEquipe.getModel();
        this.listaCarrosEquipe.clear();
        this.listaPilotosEquipe.clear();

        if (tblRemove1.getRowCount() > 0){
            for (int i=1;i<=tblRemove1.getRowCount();i++){
                tblRemove1.removeRow(0);
            }            
        }
        if (tblRemove2.getRowCount() > 0){
            for (int i=1;i<=tblRemove2.getRowCount();i++){
                tblRemove2.removeRow(0);
            }            
        }

    }
    
    public void limpaTabelaQualificacao(){
        DefaultTableModel tblRemove1 = (DefaultTableModel)tabelaPilotosQualificacao.getModel();
        this.listaCarrosQualificacao.clear();

        if (tblRemove1.getRowCount() > 0){
            for (int i=1;i<=tblRemove1.getRowCount();i++){
                tblRemove1.removeRow(0);
            }            
        }

    }
    
    private Piloto buscaPilotoNome(String nome){
        Iterator itr = autorama.getPilotos().iterator();
        Piloto piloto = null;
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Piloto){
                piloto = (Piloto)o;
                if(piloto.getNome() == nome){
                    return piloto;
                }
            }
        }
        return piloto;
    }
    
    private Pista buscaPistaNome(String nome){
        Iterator itr = autorama.getPistas().iterator();
        Pista pista = null;
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Pista){
                pista = (Pista)o;
                if(pista.getNome() == nome){
                    return pista;
                }
            }
        }
        return pista;
    }
    
    private Carro buscaCarroMarca(String marca){
        Iterator itr = autorama.getCarros().iterator();
        Carro carro = null;
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Carro){
                carro = (Carro)o;
                if(carro.getMarca() == marca){
                    return carro;
                }
            }
        }
        return carro;
    }
    
    private Equipe buscaEquipeNome(String nome){
        Iterator itr = autorama.getEquipes().iterator();
        Equipe equipe = null;
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Equipe){
                equipe = (Equipe)o;
                if(equipe.getNome() == nome){
                    return equipe;
                }
            }
        }
        return equipe;
    }
    
    private void preenchePistas(){ //Preenche select pistas da tela de configuração
        selectPistaQualificacao.removeAllItems();
        selectPistaQualificacao.addItem("<Selecionar Pista>");
        Iterator itr = autorama.getPistas().iterator();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Pista){
                Pista pista = (Pista)o;
                selectPistaQualificacao.addItem(pista.getNome());
            }
        }
    }
    
    private void preenchePilotos(){ //Preenche select pilotos da tela de cadastro de pilotos
        selectPilotoCarro.removeAllItems();
        selectPilotoCarro.addItem("<Selecionar Piloto>");
        Iterator itr = autorama.getPilotos().iterator();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Piloto){
                Piloto piloto = (Piloto)o;
                selectPilotoCarro.addItem(piloto.getNome());
            }
        }
    }
    
    private void preencheCarros(){ //Preenche select carros da tela de cadastro de carros
        selectCarroPiloto.removeAllItems();
        selectCarroPiloto.addItem("<Selecionar Carro>");
        Iterator itr = autorama.getCarros().iterator();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Carro){
                Carro carro = (Carro)o;
                selectCarroPiloto.addItem(carro.getMarca());
            }
        }
    }
    
    private void preenchePilotosEquipe(){ //Preenche select pilotos da tela de cadastro de equipe
        selectPilotoEquipe.removeAllItems();
        selectPilotoEquipe.addItem("<Selecionar Piloto>");
        Iterator itr = autorama.getPilotos().iterator();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Piloto){
                Piloto piloto = (Piloto)o;
                if(piloto.getEquipe()== null){
                    selectPilotoEquipe.addItem(piloto.getNome());
                }
            }
        }
    }
    
    private void preenchePilotosQualificacao(){ //Preenche select pilotos da tela de qualificacao
        selectPilotoQualificacao.removeAllItems();
        selectPilotoQualificacao.addItem("<Selecionar Piloto>");
        Iterator itr = autorama.getPilotos().iterator();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Piloto){
                Piloto piloto = (Piloto)o;
                if(piloto.getCarro() != null && piloto.isEmAtividade() && piloto.getEquipe() != null){
                    selectPilotoQualificacao.addItem(piloto.getNome());
                }
            }
        }
    }
    
    private void preencheCarrosEquipe(){ //Preenche select carros da tela de cadastro de equipe
        selectCarroEquipe.removeAllItems();
        selectCarroEquipe.addItem("<Selecionar Carro>");
        Iterator itr = autorama.getCarros().iterator();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Carro){
                Carro carro = (Carro)o;
                if(carro.getEquipe() == null){
                    selectCarroEquipe.addItem(carro.getMarca());
                }
            }
        }
    }
    
    private void preencheEquipesCarro(){ //Preenche select equipe da tela de cadastro de carros
        SelectEquipeCarro.removeAllItems();
        SelectEquipeCarro.addItem("<Selecionar Equipe>");
        Iterator itr = autorama.getEquipes().iterator();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Equipe){
                Equipe equipe = (Equipe)o;
                SelectEquipeCarro.addItem(equipe.getNome());
            }
        }
    }
    
    private void preencheEquipesPiloto(){ //Preenche select equipe da tela de cadastro de pilotos
        selectEquipePiloto.removeAllItems();
        selectEquipePiloto.addItem("<Selecionar Equipe>");
        Iterator itr = autorama.getEquipes().iterator();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Equipe){
                Equipe equipe = (Equipe)o;
                selectEquipePiloto.addItem(equipe.getNome());
            }
        }
    }
    
    private void preencheNacionalidadePiloto(){
        selectNacionalidadePiloto.removeAllItems();
        selectNacionalidadePiloto.addItem("<Selecionar Nacionalidade>");
        Iterator itr = autorama.getPaises().iterator();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Pais){
                Pais pais = (Pais)o;
                selectNacionalidadePiloto.addItem(pais.getNome());
            }
        }
    }
    
    private void preencheNacionalidadeEquipe(){
        selectNacionalidadeEquipe.removeAllItems();
        selectNacionalidadeEquipe.addItem("<Selecionar Nacionalidade>");
        Iterator itr = autorama.getPaises().iterator();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Pais){
                Pais pais = (Pais)o;
                selectNacionalidadeEquipe.addItem(pais.getNome());
            }
        }
    }
    
    private void preencheNacionalidadePista(){
        selectNacionalidadePista.removeAllItems();
        selectNacionalidadePista.addItem("<Selecionar Nacionalidade>");
        Iterator itr = autorama.getPaises().iterator();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Pais){
                Pais pais = (Pais)o;
                selectNacionalidadePista.addItem(pais.getNome());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SelectEquipeCarro;
    private javax.swing.JButton botaoAdicionarCarro;
    private javax.swing.JButton botaoAdicionarPiloto;
    private javax.swing.JButton botaoAdicionarPilotoQualificcao;
    private javax.swing.JButton botaoCadastrarCarros;
    private javax.swing.JButton botaoCadastrarEquipes;
    private javax.swing.JButton botaoCadastrarPilotos;
    private javax.swing.JButton botaoCadastrarPista;
    private javax.swing.JButton botaoConfirmarCadastroCarro;
    private javax.swing.JButton botaoConfirmarCadastroEquipe;
    private javax.swing.JButton botaoConfirmarCadastroPiloto;
    private javax.swing.JButton botaoConfirmarCadastroPista;
    private javax.swing.JButton botaoLerTAG;
    private javax.swing.JButton botaoQualificacao;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JButton botaoVoltar1;
    private javax.swing.JButton botaoVoltar2;
    private javax.swing.JButton botaoVoltar3;
    private javax.swing.JButton botaoVoltar4;
    private javax.swing.JSpinner duracaoQualifiacao;
    private javax.swing.JLabel imagemNacionalidadeEquipe;
    private javax.swing.JLabel imagemNacionalidadePiloto;
    private javax.swing.JLabel imagemNacionalidadePista;
    private javax.swing.JLabel imagemNacionalidadePistaQualificacao;
    private javax.swing.JTextField inputAnoEquipe;
    private javax.swing.JTextField inputApelidoEquipe;
    private javax.swing.JTextField inputApelidoPiloto;
    private javax.swing.JTextField inputDataNascimentoPiloto;
    private javax.swing.JTextField inputIdCarro;
    private javax.swing.JTextField inputIdEquipe;
    private javax.swing.JTextField inputIdPiloto;
    private javax.swing.JTextField inputIdPista;
    private javax.swing.JTextField inputMarcaCarro;
    private javax.swing.JTextField inputModeloCarro;
    private javax.swing.JTextField inputNomeEquipe;
    private javax.swing.JTextField inputNomePiloto;
    private javax.swing.JTextField inputNomePista;
    private javax.swing.JTextField inputNumeroCarro;
    private javax.swing.JTextField inputPontosEquipe;
    private javax.swing.JTextField inputPontosPiloto;
    private javax.swing.JTextField inputTagCarro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel painelCadastroCarros;
    private javax.swing.JPanel painelCadastroEquipes;
    private javax.swing.JPanel painelCadastroPilotos;
    private javax.swing.JPanel painelCadastroPista;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelQualificacao;
    private javax.swing.JComboBox<String> selectAtividadePiloto;
    private javax.swing.JComboBox<String> selectCarroEquipe;
    private javax.swing.JComboBox<String> selectCarroPiloto;
    private javax.swing.JComboBox<String> selectEquipePiloto;
    private javax.swing.JComboBox<String> selectNacionalidadeEquipe;
    private javax.swing.JComboBox<String> selectNacionalidadePiloto;
    private javax.swing.JComboBox<String> selectNacionalidadePista;
    private javax.swing.JComboBox<String> selectPilotoCarro;
    private javax.swing.JComboBox<String> selectPilotoEquipe;
    private javax.swing.JComboBox<String> selectPilotoQualificacao;
    private javax.swing.JComboBox<String> selectPistaQualificacao;
    private javax.swing.JTable tabelaCarrosEquipe;
    private javax.swing.JTable tabelaPilotosEquipe;
    private javax.swing.JTable tabelaPilotosQualificacao;
    private javax.swing.JSpinner voltasQualificacao;
    // End of variables declaration//GEN-END:variables
}
