/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Piloto;
import java.awt.Dimension;
import java.sql.Array;
import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nati_
 */
public class TelaCorrida extends javax.swing.JFrame {

    /**
     * Creates new form TelaCorrida
     */
    private final Dimension dimensaoPadrao;
    public int contadorQual = 0;
    public int contadorCorr = 0;
    public TelaCorrida() {
        initComponents();
        this.dimensaoPadrao = new Dimension(817, 547);
        painelQualificacao.setVisible(true);
        painelResultado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelResultado = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaResultado = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        contadorResultado = new javax.swing.JLabel();
        painelQualificacao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaResultadoQualificacao = new javax.swing.JTable();
        contadorQualificacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(817, 547));

        painelResultado.setBackground(new java.awt.Color(255, 255, 255));
        painelResultado.setMaximumSize(new java.awt.Dimension(817, 547));
        painelResultado.setMinimumSize(new java.awt.Dimension(817, 547));
        painelResultado.setPreferredSize(new java.awt.Dimension(817, 547));

        tabelaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carro n°", "Piloto", "Tempo de Corrida", "Melhor Tempo", "Tempo de Volta", "Voltas"
            }
        ));
        jScrollPane2.setViewportView(tabelaResultado);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("CORRIDA");

        contadorResultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        contadorResultado.setText("Tempo 00:00:00");

        javax.swing.GroupLayout painelResultadoLayout = new javax.swing.GroupLayout(painelResultado);
        painelResultado.setLayout(painelResultadoLayout);
        painelResultadoLayout.setHorizontalGroup(
            painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelResultadoLayout.createSequentialGroup()
                .addGroup(painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelResultadoLayout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(contadorResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelResultadoLayout.createSequentialGroup()
                        .addContainerGap(82, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(119, 119, 119))
        );
        painelResultadoLayout.setVerticalGroup(
            painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelResultadoLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contadorResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        painelQualificacao.setBackground(new java.awt.Color(255, 255, 255));
        painelQualificacao.setMaximumSize(new java.awt.Dimension(817, 547));
        painelQualificacao.setMinimumSize(new java.awt.Dimension(817, 547));
        painelQualificacao.setPreferredSize(new java.awt.Dimension(817, 547));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("QUALIFICAÇÃO");

        tabelaResultadoQualificacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carro n°", "Carro Modelo", "Carro Piloto", "Melhor Tempo", "Tempo de Volta"
            }
        ));
        jScrollPane3.setViewportView(tabelaResultadoQualificacao);

        contadorQualificacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        contadorQualificacao.setText("Tempo 00:00:00");

        javax.swing.GroupLayout painelQualificacaoLayout = new javax.swing.GroupLayout(painelQualificacao);
        painelQualificacao.setLayout(painelQualificacaoLayout);
        painelQualificacaoLayout.setHorizontalGroup(
            painelQualificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelQualificacaoLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(painelQualificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelQualificacaoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contadorQualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        painelQualificacaoLayout.setVerticalGroup(
            painelQualificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelQualificacaoLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(painelQualificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contadorQualificacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 817, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelQualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelQualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCorrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCorrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCorrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCorrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCorrida().setVisible(true);
                
            }
        });
    }
    public void cronometroQualificacao (){
        Timer tm = new Timer();
        tm.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                contadorQual++;
                int seg = contadorQual %60;
                int min = contadorQual /60;
                int hora = min /60;
                min %= 60; //pra ficar só os minutos
                contadorQualificacao.setText(String.format("Tempo %02d:%02d:%02d", hora, min, seg));

            }
        }, 1000, 1000);
    }
    public void cronometroCorrida (){
        Timer tm = new Timer();
        tm.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                contadorCorr++;
                int seg = contadorCorr %60;
                int min = contadorCorr /60;
                int hora = min /60;
                min %= 60; //pra ficar só os minutos
                contadorResultado.setText(String.format("Tempo %02d:%02d:%02d", hora, min, seg));
            }
        }, 1000, 1000);
    }
    public void preencheResultado (ArrayList <String> resultado){
        DefaultTableModel tabela = (DefaultTableModel)tabelaResultado.getModel();
        tabela.addRow (new String [] {resultado.get(0), resultado.get(1), resultado.get(2), resultado.get(3), resultado.get(4), resultado.get(5)}); 
    }
    public void preencheResultadoQualificacao (ArrayList <String> resultado){
        DefaultTableModel tabela = (DefaultTableModel)tabelaResultadoQualificacao.getModel();
        tabela.addRow (new String [] {resultado.get(0), resultado.get(1), resultado.get(2), resultado.get(3), resultado.get(4)}); 
    }
    
    public void limpaTabelaQualificacao(){
        DefaultTableModel tabela = (DefaultTableModel)tabelaResultadoQualificacao.getModel();
        if(tabela.getRowCount() > 0){
            while (tabela.getRowCount() > 0){
                tabela.removeRow(0);
            }
        }
    }
    public void limpaTabelaCorrida(){
        DefaultTableModel tabela = (DefaultTableModel)tabelaResultado.getModel();
        if(tabela.getRowCount() > 0){
            while (tabela.getRowCount() > 0){
                tabela.removeRow(0);
            }
        }
    }
    public void sucesso (){
        JOptionPane.showMessageDialog(rootPane, "Corrida Finalizada!");
    }
    
    public void sucessoQualificacao (){
        JOptionPane.showMessageDialog(rootPane, "Qualificacao Finalizada! Deseja Iniciar a corrida?");
    }
    
    public void setaQualificacao (boolean seta){
        if(seta){
            cronometroQualificacao();
        }
        painelQualificacao.setVisible(seta);
    }
    
    public void setaCorrida (boolean seta){
        if(seta){
            cronometroCorrida();
        }
        painelResultado.setVisible(seta);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contadorQualificacao;
    private javax.swing.JLabel contadorResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel painelQualificacao;
    private javax.swing.JPanel painelResultado;
    private javax.swing.JTable tabelaResultado;
    private javax.swing.JTable tabelaResultadoQualificacao;
    // End of variables declaration//GEN-END:variables
}
