/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AutoramaController;
import Model.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author nati_
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    private AutoramaController autorama;
    
    public TelaInicial(AutoramaController autorama) {
        this.autorama = autorama;
        initComponents();
        esconderTelas();
        painelPrincipal.setVisible(true);
    }
    public TelaInicial() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCadastroCarros = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        inputMarcaCarro = new javax.swing.JTextField();
        inputNumeroCarro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        selectPilotoCarro = new javax.swing.JComboBox<>();
        SelectEquipeCarro = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        inputIdCarro = new javax.swing.JTextField();
        botaoConfirmarCadastroCarro = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        inputTagCarro = new javax.swing.JTextField();
        inputModeloCarro = new javax.swing.JTextField();
        botaoVoltar = new javax.swing.JButton();
        painelCadastroPilotos = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        inputNomePiloto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        botaoConfirmarCadastroPiloto = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        inputApelidoPiloto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        selectCarroPiloto = new javax.swing.JComboBox<>();
        inputDataNascimentoPiloto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        selectEquipePiloto = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        selectAtividadePiloto = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        inputIdPiloto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputPontosPiloto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        botaoVoltar1 = new javax.swing.JButton();
        selectNacionalidadePiloto = new javax.swing.JComboBox<>();
        imagemNacionalidadePiloto = new javax.swing.JLabel();
        painelCadastroEquipes = new javax.swing.JPanel();
        inputAnoEquipe = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        inputIdEquipe = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPilotosEquipe = new javax.swing.JList<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaCarrosEquipe = new javax.swing.JList<>();
        jLabel27 = new javax.swing.JLabel();
        inputPontosEquipe = new javax.swing.JTextField();
        inputNomeEquipe = new javax.swing.JTextField();
        inputApelidoEquipe = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        botaoConfirmarCadastroEquipe = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        botaoVoltar2 = new javax.swing.JButton();
        selectNacionalidadeEquipe = new javax.swing.JComboBox<>();
        imagemNacionalidadeEquipe = new javax.swing.JLabel();
        painelPrincipal = new javax.swing.JPanel();
        botaoCadastrarCarros = new javax.swing.JButton();
        botaoCadastrarPilotos = new javax.swing.JButton();
        botaoCadastrarEquipes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        painelCadastroCarros.setBackground(new java.awt.Color(255, 255, 255));
        painelCadastroCarros.setMaximumSize(new java.awt.Dimension(817, 547));
        painelCadastroCarros.setMinimumSize(new java.awt.Dimension(817, 547));

        jLabel14.setText("Marca");

        jLabel15.setText("Número");

        jLabel16.setText("Piloto");

        jLabel17.setText("Equipe");

        selectPilotoCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPilotoCarroActionPerformed(evt);
            }
        });

        SelectEquipeCarro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SelectEquipeCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectEquipeCarroActionPerformed(evt);
            }
        });

        jLabel18.setText("Cor");

        inputIdCarro.setEditable(false);

        botaoConfirmarCadastroCarro.setText("Cadastrar");
        botaoConfirmarCadastroCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarCadastroCarroActionPerformed(evt);
            }
        });

        jLabel13.setText("ID");

        jSeparator2.setBackground(new java.awt.Color(0, 102, 255));

        jLabel3.setText("TAG");

        jLabel12.setText("Modelo");

        botaoVoltar.setText("Cancelar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCadastroCarrosLayout = new javax.swing.GroupLayout(painelCadastroCarros);
        painelCadastroCarros.setLayout(painelCadastroCarrosLayout);
        painelCadastroCarrosLayout.setHorizontalGroup(
            painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroCarrosLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(inputIdCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroCarrosLayout.createSequentialGroup()
                            .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(inputTagCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(38, 38, 38)
                            .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(inputModeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelCadastroCarrosLayout.createSequentialGroup()
                        .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(selectPilotoCarro, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputMarcaCarro, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15)
                            .addComponent(inputNumeroCarro)
                            .addComponent(jLabel17)
                            .addComponent(SelectEquipeCarro, 0, 182, Short.MAX_VALUE)
                            .addComponent(botaoConfirmarCadastroCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        painelCadastroCarrosLayout.setVerticalGroup(
            painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroCarrosLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputIdCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTagCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputModeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputMarcaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNumeroCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectPilotoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectEquipeCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(painelCadastroCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoConfirmarCadastroCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        painelCadastroPilotos.setBackground(new java.awt.Color(255, 255, 255));
        painelCadastroPilotos.setMaximumSize(new java.awt.Dimension(817, 547));
        painelCadastroPilotos.setMinimumSize(new java.awt.Dimension(817, 547));

        jSeparator1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel9.setText("Em atividade");

        jLabel10.setText("Pontos");

        botaoConfirmarCadastroPiloto.setText("Cadastrar");
        botaoConfirmarCadastroPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarCadastroPilotoActionPerformed(evt);
            }
        });

        jLabel11.setText("ID");

        jLabel1.setText("Nome do Piloto");

        inputApelidoPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputApelidoPilotoActionPerformed(evt);
            }
        });

        jLabel2.setText("Carro");

        selectCarroPiloto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Apelido");

        selectEquipePiloto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Data de Nascimento");

        selectAtividadePiloto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Nao" }));
        selectAtividadePiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAtividadePilotoActionPerformed(evt);
            }
        });

        jLabel6.setText("Foto");

        inputIdPiloto.setEditable(false);

        jLabel7.setText("Equipe");

        inputPontosPiloto.setEditable(false);

        jLabel8.setText("Nacionalidade");

        botaoVoltar1.setText("Cancelar");
        botaoVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltar1ActionPerformed(evt);
            }
        });

        selectNacionalidadePiloto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        imagemNacionalidadePiloto.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        imagemNacionalidadePiloto.setText(" ");

        javax.swing.GroupLayout painelCadastroPilotosLayout = new javax.swing.GroupLayout(painelCadastroPilotos);
        painelCadastroPilotos.setLayout(painelCadastroPilotosLayout);
        painelCadastroPilotosLayout.setHorizontalGroup(
            painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroPilotosLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(painelCadastroPilotosLayout.createSequentialGroup()
                            .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(painelCadastroPilotosLayout.createSequentialGroup()
                                    .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(selectAtividadePiloto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(selectCarroPiloto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(inputNomePiloto, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                                        .addGroup(painelCadastroPilotosLayout.createSequentialGroup()
                                                            .addComponent(selectNacionalidadePiloto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addGap(4, 4, 4)
                                                            .addComponent(imagemNacionalidadePiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addComponent(jLabel8)))
                                            .addComponent(jLabel2))
                                        .addComponent(jLabel9)
                                        .addComponent(botaoVoltar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(40, 40, 40))
                                .addGroup(painelCadastroPilotosLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(209, 209, 209))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelCadastroPilotosLayout.createSequentialGroup()
                                    .addComponent(inputIdPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(inputApelidoPiloto)
                                .addComponent(inputDataNascimentoPiloto, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                .addComponent(selectEquipePiloto, 0, 166, Short.MAX_VALUE)
                                .addComponent(botaoConfirmarCadastroPiloto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(inputPontosPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        painelCadastroPilotosLayout.setVerticalGroup(
            painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroPilotosLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputIdPiloto)
                    .addComponent(inputPontosPiloto))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputApelidoPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelCadastroPilotosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(inputNomePiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroPilotosLayout.createSequentialGroup()
                        .addComponent(selectNacionalidadePiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelCadastroPilotosLayout.createSequentialGroup()
                        .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputDataNascimentoPiloto)
                            .addComponent(imagemNacionalidadePiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(selectCarroPiloto)
                    .addComponent(selectEquipePiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(selectAtividadePiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelCadastroPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoConfirmarCadastroPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelCadastroPilotosLayout.createSequentialGroup()
                        .addComponent(botaoVoltar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(81, 81, 81))
        );

        painelCadastroEquipes.setBackground(new java.awt.Color(255, 255, 255));
        painelCadastroEquipes.setMaximumSize(new java.awt.Dimension(817, 547));
        painelCadastroEquipes.setMinimumSize(new java.awt.Dimension(817, 547));

        jLabel24.setText("Foto");

        jLabel29.setText("Ano");

        inputIdEquipe.setEditable(false);

        listaPilotosEquipe.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaPilotosEquipe);

        jLabel25.setText("Pilotos");

        jLabel26.setText("Pontos");

        listaCarrosEquipe.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaCarrosEquipe.setToolTipText("");
        jScrollPane3.setViewportView(listaCarrosEquipe);

        jLabel27.setText("ID");

        inputPontosEquipe.setEditable(false);

        inputApelidoEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputApelidoEquipeActionPerformed(evt);
            }
        });

        jLabel21.setText("Carros");

        botaoConfirmarCadastroEquipe.setText("Cadastrar");
        botaoConfirmarCadastroEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarCadastroEquipeActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 102, 255));

        jLabel22.setText("Nacionalidade");

        jLabel28.setText("Apelido");

        jLabel23.setText("Nome ");

        botaoVoltar2.setText("Cancelar");
        botaoVoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltar2ActionPerformed(evt);
            }
        });

        selectNacionalidadeEquipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        imagemNacionalidadeEquipe.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        imagemNacionalidadeEquipe.setText(" ");

        javax.swing.GroupLayout painelCadastroEquipesLayout = new javax.swing.GroupLayout(painelCadastroEquipes);
        painelCadastroEquipes.setLayout(painelCadastroEquipesLayout);
        painelCadastroEquipesLayout.setHorizontalGroup(
            painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                            .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                                    .addComponent(inputIdEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroEquipesLayout.createSequentialGroup()
                                    .addComponent(jLabel27)
                                    .addGap(280, 280, 280)))
                            .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel26)
                                .addComponent(inputPontosEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                            .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                                    .addComponent(botaoVoltar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(40, 40, 40))
                                .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                                    .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel23)
                                        .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                                                .addComponent(selectNacionalidadeEquipe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(imagemNacionalidadeEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(inputNomeEquipe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(botaoConfirmarCadastroEquipe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputApelidoEquipe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                .addComponent(jLabel28)
                                .addComponent(inputAnoEquipe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                .addComponent(jLabel29)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                .addComponent(jLabel21)))))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        painelCadastroEquipesLayout.setVerticalGroup(
            painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroEquipesLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputIdEquipe)
                    .addComponent(inputPontosEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel28))
                .addGap(6, 6, 6)
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNomeEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputApelidoEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputAnoEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectNacionalidadeEquipe)
                    .addComponent(imagemNacionalidadeEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addGroup(painelCadastroEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoConfirmarCadastroEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltar2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        painelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        painelPrincipal.setMaximumSize(new java.awt.Dimension(817, 547));
        painelPrincipal.setMinimumSize(new java.awt.Dimension(817, 547));

        botaoCadastrarCarros.setText("Cadastrar Carros");
        botaoCadastrarCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarCarrosActionPerformed(evt);
            }
        });

        botaoCadastrarPilotos.setText("Cadastrar Pilotos");
        botaoCadastrarPilotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarPilotosActionPerformed(evt);
            }
        });

        botaoCadastrarEquipes.setText("Cadastrar Equipes");
        botaoCadastrarEquipes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarEquipesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botaoCadastrarPilotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoCadastrarCarros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoCadastrarEquipes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(botaoCadastrarCarros)
                .addGap(18, 18, 18)
                .addComponent(botaoCadastrarPilotos)
                .addGap(18, 18, 18)
                .addComponent(botaoCadastrarEquipes)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelCadastroCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelCadastroPilotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelCadastroEquipes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(painelCadastroCarros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(painelCadastroPilotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(painelCadastroEquipes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoConfirmarCadastroCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarCadastroCarroActionPerformed
        esconderTelas();
        painelPrincipal.setVisible(true);
    }//GEN-LAST:event_botaoConfirmarCadastroCarroActionPerformed

    private void botaoConfirmarCadastroPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarCadastroPilotoActionPerformed
        esconderTelas();
        painelPrincipal.setVisible(true);
    }//GEN-LAST:event_botaoConfirmarCadastroPilotoActionPerformed

    private void inputApelidoPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputApelidoPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputApelidoPilotoActionPerformed

    private void inputApelidoEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputApelidoEquipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputApelidoEquipeActionPerformed

    private void botaoConfirmarCadastroEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarCadastroEquipeActionPerformed
        esconderTelas();
        painelPrincipal.setVisible(true);
    }//GEN-LAST:event_botaoConfirmarCadastroEquipeActionPerformed

    private void botaoCadastrarCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarCarrosActionPerformed
        int id = autorama.getCarros().size() + 1;
        inputIdCarro.setText(Integer.toString(id));
        esconderTelas();
        preenchePilotos();
        preencheEquipesCarro();
        painelCadastroCarros.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarCarrosActionPerformed

    private void botaoCadastrarPilotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarPilotosActionPerformed
        int id = autorama.getPilotos().size() + 1;
        inputIdPiloto.setText(Integer.toString(id));
        inputPontosPiloto.setText("000");
        preencheEquipesPiloto();
        preencheNacionalidadePiloto();
        preencheCarros();
        esconderTelas();
        selectNacionalidadePiloto.addActionListener((ActionEvent e) -> {
            try {
                String pais_selecionado = selectNacionalidadePiloto.getSelectedItem().toString();
                Pais pais = autorama.getPais(pais_selecionado);
                
                BufferedImage img_bf = ImageIO.read(new File(pais.getBandeira()));
                ImageIcon img = new ImageIcon(img_bf);
                img = new ImageIcon(img.getImage().getScaledInstance(44, 32, java.awt.Image.SCALE_DEFAULT));
                imagemNacionalidadePiloto.setIcon(img);
                
            } catch (IOException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {}
        });
        painelCadastroPilotos.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarPilotosActionPerformed

    private void botaoCadastrarEquipesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarEquipesActionPerformed
        int id = autorama.getEquipes().size() + 1;
        inputIdEquipe.setText(Integer.toString(id));
        inputPontosEquipe.setText("000");
        preencheNacionalidadeEquipe();
        esconderTelas();
        selectNacionalidadeEquipe.addActionListener((ActionEvent e) -> {
            try {
                String pais_selecionado = selectNacionalidadeEquipe.getSelectedItem().toString();
                Pais pais = autorama.getPais(pais_selecionado);
                
                BufferedImage img_bf = ImageIO.read(new File(pais.getBandeira()));
                ImageIcon img = new ImageIcon(img_bf);
                img = new ImageIcon(img.getImage().getScaledInstance(44, 32, java.awt.Image.SCALE_DEFAULT));
                imagemNacionalidadeEquipe.setIcon(img);
                
            } catch (IOException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {}
        });
        painelCadastroEquipes.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarEquipesActionPerformed

    private void selectPilotoCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPilotoCarroActionPerformed

    }//GEN-LAST:event_selectPilotoCarroActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        esconderTelas();
        painelPrincipal.setVisible(true);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltar1ActionPerformed
        esconderTelas();
        painelPrincipal.setVisible(true);
    }//GEN-LAST:event_botaoVoltar1ActionPerformed

    private void botaoVoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltar2ActionPerformed
        esconderTelas();
        painelPrincipal.setVisible(true);
    }//GEN-LAST:event_botaoVoltar2ActionPerformed

    private void SelectEquipeCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectEquipeCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectEquipeCarroActionPerformed

    private void selectAtividadePilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAtividadePilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectAtividadePilotoActionPerformed
                              
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
    
    private void esconderTelas(){
        painelCadastroCarros.setVisible(false);
        painelCadastroPilotos.setVisible(false);
        painelCadastroEquipes.setVisible(false);
        painelPrincipal.setVisible(false);
    }
    
    private void preenchePilotos(){
        selectPilotoCarro.removeAllItems();
        selectPilotoCarro.addItem("<Selecionar Piloto>");
        Iterator itr = autorama.getPilotos().iterator();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Piloto){
                Piloto piloto = (Piloto)o;
                selectPilotoCarro.addItem(piloto.getNome());
            }
        }
    }
    
    private void preencheCarros(){
        selectCarroPiloto.removeAllItems();
        selectCarroPiloto.addItem("<Selecionar Carro>");
        Iterator itr = autorama.getCarros().iterator();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Carro){
                Carro carro = (Carro)o;
                selectCarroPiloto.addItem(carro.getMarca());
            }
        }
    }
    
    private void preencheEquipesCarro(){
        SelectEquipeCarro.removeAllItems();
        SelectEquipeCarro.addItem("<Selecionar Equipe>");
        Iterator itr = autorama.getEquipes().iterator();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Equipe){
                Equipe equipe = (Equipe)o;
                SelectEquipeCarro.addItem(equipe.getNome());
            }
        }
    }
    
    private void preencheEquipesPiloto(){
        selectEquipePiloto.removeAllItems();
        selectEquipePiloto.addItem("<Selecionar Equipe>");
        Iterator itr = autorama.getEquipes().iterator();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Equipe){
                Equipe equipe = (Equipe)o;
                selectEquipePiloto.addItem(equipe.getNome());
            }
        }
    }
    
    private void preencheNacionalidadePiloto(){
        selectNacionalidadePiloto.removeAllItems();
        selectNacionalidadePiloto.addItem("<Selecionar Nacionalidade>");
        Iterator itr = autorama.getPaises().iterator();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Pais){
                Pais pais = (Pais)o;
                selectNacionalidadePiloto.addItem(pais.getNome());
            }
        }
    }
    
    private void preencheNacionalidadeEquipe(){
        selectNacionalidadeEquipe.removeAllItems();
        selectNacionalidadeEquipe.addItem("<Selecionar Nacionalidade>");
        Iterator itr = autorama.getPaises().iterator();
        while(itr.hasNext()){
            Object o = itr.next();
            if(o  instanceof Pais){
                Pais pais = (Pais)o;
                selectNacionalidadeEquipe.addItem(pais.getNome());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SelectEquipeCarro;
    private javax.swing.JButton botaoCadastrarCarros;
    private javax.swing.JButton botaoCadastrarEquipes;
    private javax.swing.JButton botaoCadastrarPilotos;
    private javax.swing.JButton botaoConfirmarCadastroCarro;
    private javax.swing.JButton botaoConfirmarCadastroEquipe;
    private javax.swing.JButton botaoConfirmarCadastroPiloto;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JButton botaoVoltar1;
    private javax.swing.JButton botaoVoltar2;
    private javax.swing.JLabel imagemNacionalidadeEquipe;
    private javax.swing.JLabel imagemNacionalidadePiloto;
    private javax.swing.JTextField inputAnoEquipe;
    private javax.swing.JTextField inputApelidoEquipe;
    private javax.swing.JTextField inputApelidoPiloto;
    private javax.swing.JTextField inputDataNascimentoPiloto;
    private javax.swing.JTextField inputIdCarro;
    private javax.swing.JTextField inputIdEquipe;
    private javax.swing.JTextField inputIdPiloto;
    private javax.swing.JTextField inputMarcaCarro;
    private javax.swing.JTextField inputModeloCarro;
    private javax.swing.JTextField inputNomeEquipe;
    private javax.swing.JTextField inputNomePiloto;
    private javax.swing.JTextField inputNumeroCarro;
    private javax.swing.JTextField inputPontosEquipe;
    private javax.swing.JTextField inputPontosPiloto;
    private javax.swing.JTextField inputTagCarro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JList<String> listaCarrosEquipe;
    private javax.swing.JList<String> listaPilotosEquipe;
    private javax.swing.JPanel painelCadastroCarros;
    private javax.swing.JPanel painelCadastroEquipes;
    private javax.swing.JPanel painelCadastroPilotos;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JComboBox<String> selectAtividadePiloto;
    private javax.swing.JComboBox<String> selectCarroPiloto;
    private javax.swing.JComboBox<String> selectEquipePiloto;
    private javax.swing.JComboBox<String> selectNacionalidadeEquipe;
    private javax.swing.JComboBox<String> selectNacionalidadePiloto;
    private javax.swing.JComboBox<String> selectPilotoCarro;
    // End of variables declaration//GEN-END:variables
}
